### ISSUE TITLE
Pull to refresh loading status is complete

### ISSUE THREAD

**Issue by naveedmcs** [hoangtaiki/Refreshable#4]
how can i check when Pull to refresh status is complete ?

**Comment by hoangtaiki** [comment]
Why you need to check Pull To Refresh status?
We exposed function to start and stop Pull To Refresh view.
When you add pull to refresh you can handle state through it closure.

**Comment by naveedmcs** [comment]
actually i was doing . on button tap action ..when It was on refreshing
state .. button tap more than one .. refreshing UI scroll is distributed ..
so  I add extra funtions using by extension . to Block UI on refreshing
state. that was requirement.
